[package]
name = "ordis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
poise = "=0.5.7"
rand = "0.8.5"
rusqlite = "0.31.0"
evalexpr = "11.3.0"
