[package]
name = "Ordis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.34.0"
serenity = "=0.11.7"
tokio = { version = "1.37.0", features = ["full"] }
